"""Adiciona campos extras ao QuizResult

Revision ID: b83f8f589a47
Revises: 
Create Date: 2025-07-29 06:00:49.082959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b83f8f589a47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nervosismo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('preocupacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('interesse', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sono', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('atividade_fisica', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fatores', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('motivacao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hora_extra', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('pronto_socorro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('relacionamentos', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('hobbies', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('recomendacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_results', schema=None) as batch_op:
        batch_op.drop_column('recomendacao')
        batch_op.drop_column('hobbies')
        batch_op.drop_column('relacionamentos')
        batch_op.drop_column('pronto_socorro')
        batch_op.drop_column('hora_extra')
        batch_op.drop_column('motivacao')
        batch_op.drop_column('fatores')
        batch_op.drop_column('atividade_fisica')
        batch_op.drop_column('sono')
        batch_op.drop_column('interesse')
        batch_op.drop_column('preocupacao')
        batch_op.drop_column('nervosismo')

    # ### end Alembic commands ###
