"""added user_id to quotes

Revision ID: ba6c118893d9
Revises: 
Create Date: 2025-09-04 11:28:47.590281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba6c118893d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        # explicit index name
        batch_op.create_index('ix_quotes_user_id', ['user_id'], unique=False)
        # explicit foreign key name
        batch_op.create_foreign_key(
            'fk_quotes_user_id_users',
            'users',
            ['user_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quotes_user_id_users', type_='foreignkey')
        batch_op.drop_index('ix_quotes_user_id')
        batch_op.drop_column('user_id')
    # ### end Alembic commands ###
