"""add doctor's availability

Revision ID: d4966d3ed1d7
Revises: 1eca12bb9340
Create Date: 2025-08-27 21:20:19.530863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4966d3ed1d7'
down_revision = '1eca12bb9340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_date_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor_date_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_date_availability_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_doctor_date_availability_doctor_id'), ['doctor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctor_date_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_date_availability_doctor_id'))
        batch_op.drop_index(batch_op.f('ix_doctor_date_availability_day'))

    op.drop_table('doctor_date_availability')
    # ### end Alembic commands ###
